# Погружение в Python



---



## Семинар 04

**Задание 1.**<br>
Напишите функцию для транспонирования матрицы.

In [1]:
def matrix_transposition(matrix):
  for i in range(len(matrix)):
    for j in range(len(matrix[0])):
      result[j][i] = matrix[i][j]
  return result

matrix = [[1,2,3], [4,5,6], [7,8,9]]
result = [[0,0,0], [0,0,0], [0,0,0]]
print(f'Исходная матрица:\n{matrix}\n')
print(f'Транспонированная матрица:\n{matrix_transposition(matrix)}')

Исходная матрица:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Транспонированная матрица:
[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


*Однако мне не совсем нравится такой метод. Так как приходится вводить не только исходную матрицу, но и в соответствии ей пустую, куда записывается результат (другого решения я не придумал). Поэтому, считаю, что лучший выход - не изобретать велосипед, а воспользоваться встроенной функцией из numpy.*

In [2]:
import numpy as np


def m_transpos(matrix):
  """Just matrix transpose and nothing else."""
  res = np.array(matrix)
  return np.transpose(res)


matrix = [[1,2,3], [4,5,6], [7,8,9]]
print(f'Исходная матрица:\n{np.array(matrix)}\n')
print(f'Транспонированная матрица:\n{m_transpos(matrix)}')


Исходная матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Транспонированная матрица:
[[1 4 7]
 [2 5 8]
 [3 6 9]]




---



**Задание 2.**<br>
Напишите функцию, принимающую на вход только ключевые параметры и возвращающую словарь, где ключ — значение переданного аргумента, а значение — имя аргумента. Если ключ не хешируем, используйте его строковое представление.

In [3]:
def some_func(**kwargs):
  dict = {}
  for key, value in kwargs.items():
    dict[value] = key
  return dict


some_func(х=1, y=2)

{1: 'х', 2: 'y'}



---



**Задание 3.**<br>
Возьмите задачу о банкомате из семинара 2. Разбейте её на отдельные операции — функции. Дополнительно сохраняйте все операции поступления и снятия средств в список.

***Комментарий к условию.*** *Если список планируется использовать наподобие log-файла, то возможно операции поступления и снятия лучше записывать в словарь - будет нагляднее и практичнее, как мне кажется. Поэтому сделал все же словарь, а не список. Но если что - могу переделать на список.*

**Условие задачи.** Напишите программу банкомат. Начальная сумма равна 0. Допустимые действия: пополнить, снять, выйти. Сумма пополнения и снятия кратны 50 у.е. Процент за снятие 1,5% от суммы снятия, но не менее 30 и не более 600у.е. После каждой третьей операции пополнения или снятия насичляются проценты 3%. Нельзя снять больше, чем на счете. При привышении суммы в 5 млн. вычитать налог на богатство 10% перед каждой операцией, даже ошибочной. Любое действие выводит сумму денег.

In [4]:
def put_money(money: int):
  while True:
    global money_to_put
    money_to_put = int(input('\nКакую сумму Вы хотите внести? (Сумма должна быть кратна 50.): '))
    if money_to_put % 50 != 0:
      print('Сумма должна быть кратна 50. Пожалуйста, повторите ввод.')
    else:
      break
  money += money_to_put
  return money


def withdraw_money(money: int):
  while True:
    global amount_to_take
    amount_to_take = int(input('Какую сумму Вы хотите снять? (Сумма должна быть кратна 50.): '))
    percent = amount_to_take * 0.015
    if percent < 30:
      money_with_procent = amount_to_take + 30
    elif percent > 600:
      money_with_procent = amount_to_take + 600
    else:
      money_with_procent = amount_to_take + percent

    if amount_to_take % 50 != 0:
      print('Сумма должна быть кратна 50. Пожалуйста, повторите ввод.')
    elif money_with_procent > money:
      print('Недостаточно средств на счете. Введите меньшую сумму. ')
    else:
      break
  money -= money_with_procent
  return money


def wealth_tax(money: int):
  if money > 5_000_000:
    money *= 0.9
  return money


def check_count(count: int, money: int):
  count += 1
  if count == 3:
    money *= 1.03
    count = 0
  return count, money


def main():
  money = 0
  count = 0
  count_list_put = 1
  count_list_take = 1
  log_list = {}
  while True:
    print('Список доступных операций:')
    print('1. Внести наличные.')
    print('2. Снять наличные.')
    print('3. Выход.')
    while True:
      user_choice = int(input('\nВыберите номер операции: '))
      if user_choice not in [1, 2, 3]:
        print('\nНомер операции указан неверно. Введите номер еще раз.')
        money = wealth_tax(money)
        print(f'\nСумма на счете: {money}')
      else:
        break
    match user_choice:
      case 1:
        money = put_money(money)
        money = wealth_tax(money)
        count, money = check_count(count, money)
        log_list[f'Пополнение средств №{count_list_put}'] = money_to_put
        count_list_put += 1
        print(f'\nСумма на счете: {money}\n')
      case 2:
        if money == 0:
          print(f'\nСумма на счете: {money}')
          print('Необходимо пополнить счет.\n')
        else:
          money = wealth_tax(money)
          money = withdraw_money(money)
          count, money = check_count(count, money)
          log_list[f'Снятие средств №{count_list_take}'] = amount_to_take
          count_list_take += 1
          print(f'\nСумма на счете: {money}\n')
      case 3:
        log_query = input('\nВывести на экран историю операций по внесению и списанию средств (да/нет)?: ')
        if log_query == 'да' or log_query == 'Да':
          if log_list == {}:
            print('\nВы не произвели никаких действий со счетом.')
          else:
            print(f'\nПроизведенные операци со счетом:\n{log_list}')
        print(f'\nСумма на счете: {money}')
        print('До свидания!')
        return


if __name__ == '__main__':
  main()

Список доступных операций:
1. Внести наличные.
2. Снять наличные.
3. Выход.



Сумма на счете: 500

Список доступных операций:
1. Внести наличные.
2. Снять наличные.
3. Выход.

Сумма на счете: 500
До свидания!
